export const selectionOptions = {
  weather: ["klar", "bewölkt", "regnerisch", "stürmisch", "neblig", "Schnee"],
  moon: ["Neumond", "zunehmend", "Vollmond", "abnehmend"],
  wind: [
    "Nord",
    "Nordost",
    "Ost",
    "Südost",
    "Süd",
    "Südwest",
    "West",
    "Nordwest",
  ],
  watercolor: ["klar", "trüb", "leicht trüb"],
  waterlevel: ["hoch", "niederig", "normal"],
  germanFishSpecies: [
    "Aal",
    "Aland",
    "Äsche",
    "Bachforelle",
    "Bachsaibling",
    "Barbe",
    "Barsch",
    "Bitterling",
    "Brassen",
    "Butt",
    "Döbel",
    "Dorsch",
    "Elritze",
    "Flunder",
    "Gründling",
    "Güster",
    "Hecht",
    "Hering",
    "Hornhecht",
    "Karausche",
    "Karpfen",
    "Kaulbarsch",
    "Laube (Ukelei)",
    "Lachs",
    "Leng",
    "Makrele",
    "Maräne",
    "Meeräsche",
    "Meerforelle",
    "Nase",
    "Regenbogenforelle",
    "Rotauge",
    "Rotbarsch",
    "Rotfeder",
    "Rutte (Quappe)",
    "Sardine",
    "Schleie",
    "Schmerle",
    "Scholle",
    "Schuppenkarpfen",
    "Seeforelle",
    "Seeaal",
    "Seehecht",
    "Seelachs",
    "Seesaibling",
    "Seezunge",
    "Spiegelkarpfen",
    "Steinbutt",
    "Stint",
    "Thunfisch",
    "Wels",
    "Weißfisch",
    "Wittling",
    "Zander",
    "Zope",
    "Schwertfisch",
  ],
};
